treewide: change 'kernel@1' with just 'kernel'
U-boot upstream change:

79af75f777 ("fit: Don't allow verification of images with @ nodes")

This change is descripted as :

When searching for a node called 'fred', any unit address appended to the
name is ignored by libfdt, meaning that 'fred' can match 'fred@1'. This
means that we cannot be sure that the node originally intended is the one
that is used.

Upstream u-boot does not allow nodes having '@' in its name.

Verifying Hash Integrity ... error!
Node name contains @ in 'kernel@1' image node
Bad Data Hash
ERROR: can't get kernel image!

Change all the 'kernel@1' nodes with just 'kernel'

Signed-off-by: Eugen Hristev <eugen.hristev@microchip.com>
Acked-by: Cristian Birsan <cristian.birsan@microchip.com>